### ISSUE TITLE
Support Content-Range for file downloads

### ISSUE THREAD

**Issue by xiegeo** [RTradeLtd/TxPB#41]
Add [Content-Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range) support to DownloadRequest message.

During x3s development, if a download request with Content-Range is received, the full file still needs to be retrieved from the backend.

Implementation should be easy, as [go-unixfs/io#DagReader](https://www.godoc.org/github.com/ipfs/go-unixfs/io#DagReader) supports `Seek`.

This feature is generally useful, such as download resumption and video streaming.

**Comment by bonedaddy** [comment]
see latest master commit
