### ISSUE TITLE
Add Contributors License Agreement

### ISSUE THREAD

**Issue by bonedaddy** [RTradeLtd/TxPB#72]
It is theoretically possible for the "public" to contribute code that is used by TemporalX. As such we need to have a contributors license agreement in place for if this does happen. The contributors license agreement should state that by contributing code, you agree that you waive all rights to the code and that it belongs to RTrade Technologies.

**Comment by xiegeo** [comment]
I think it's probably a good idea to have one for all company projects. So a developer only need to sign once to contribute to any number of projects.

**Comment by bonedaddy** [comment]
Yea it is, I guess we can just store the agreement here, and then link back to it from all of our public repos
